name: 'netflix_data_analysis'
version: '1.0.0'
config-version: 2
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:   
  - "target"
  - "dbt_packages"

models:
  netflix_data_analysis:
    staging:
      +schema: dev
      +materialized: view

    dim:
      +schema: dev
      +materialized: table

    fct:
      +schema: dev
      +materialized: table
       
